spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lyy
    password:
    url: jdbc:mysql://111.229.203.103:3306/user_center
  session:
    timeout: 86400
